class Card:
    def __init__(self, name):
        self.name = name


ALL_CARDS = [
    Card("Elefant"),
    Card("Elefant"),
    Card("Elefant"),
    Card("Elefant"),
    Card("Elefant"),
    Card("Mücke"),
    Card("Mücke"),
    Card("Mücke"),
    Card("Mücke"),
    Card("Sardinen"),
    Card("Sardinen"),
    Card("Sardinen"),
    Card("Sardinen"),
    Card("Sardinen"),
    Card("Chamäleon"),
    Card("Barsch"),
    Card("Barsch"),
    Card("Barsch"),
    Card("Barsch"),
    Card("Barsch"),
    Card("Robbe"),
    Card("Robbe"),
    Card("Robbe"),
    Card("Robbe"),
    Card("Robbe"),
    Card("Eisbär"),
    Card("Eisbär"),
    Card("Eisbär"),
    Card("Eisbär"),
    Card("Eisbär"),
    Card("Krokodil"),
    Card("Krokodil"),
    Card("Krokodil"),
    Card("Krokodil"),
    Card("Krokodil"),
    Card("Orka"),
    Card("Orka"),
    Card("Orka"),
    Card("Orka"),
    Card("Orka"),
    Card("Löwe"),
    Card("Löwe"),
    Card("Löwe"),
    Card("Löwe"),
    Card("Löwe"),
    Card("Igel"),
    Card("Igel"),
    Card("Igel"),
    Card("Igel"),
    Card("Igel"),
    Card("Fuchs"),
    Card("Fuchs"),
    Card("Fuchs"),
    Card("Fuchs"),
    Card("Fuchs"),
    Card("Maus"),
    Card("Maus"),
    Card("Maus"),
    Card("Maus"),
    Card("Maus"),
]
