# Generated by Django 3.0.5 on 2020-04-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("round", models.CharField(max_length=255)),
                ("players", models.CharField(max_length=255)),
                ("cards", models.TextField(editable=False, null=True)),
            ],
        ),
    ]
